version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "cs"
      MYSQL_ROOT_PASSWORD: "csc648team8"
    ports:
      - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 3s
        retries: 20

  web:
    restart: unless-stopped
    image: web
    ports:
      - 80:80
      
  server:
    image: server
    ports:
      - 8080:8080
    depends_on:
        mysql:
            condition: service_healthy