version: '3'

services:
  
  web:
    restart: unless-stopped
    image: web
    ports:
      - 80:80
      - 443:443
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_lib:/var/lib/letsencrypt